### ISSUE TITLE
각오 작성페이지 권한 설정

### ISSUE THREAD

**Issue by woodimora** [woodimora/project-scrum#4]
로그인한 사용자만 작성할 수 있도록 권한 설정하기

**Comment by jeongjae95** [comment]
메인페이지에서 상세페이지로 연동하기

프로필 수정 연동하기

프로필 사진 넣기 기능 활성화

상세페이지에서 각오글 활성화
ㄴ>이미지,닉네임,아이디,시간 나타내기

**Comment by woodimora** [comment]
각오 작성 페이지 권한 설정 완료.
